### ISSUE TITLE
These Apps no longer build

### ISSUE THREAD

**Issue by bradleat** [LedgerHQ/blue-sample-apps#3]
After following the instructions from https://github.com/LedgerHQ/ledger-dev-doc/blob/master/nanos/setup.rst I find that these applications do not build.

For whatever reason sample apps appear to be looking for `lib_bluenrg` which appears to be left over from an older version of the `nanos-secure-sdk`

find: `/home/nanos-secure-sdk/lib_bluenrg*': No such file or directory
find: `/home/nanos-secure-sdk/lib_bluenrg*': No such file or directory
[CC]	obj/os_io_seproxyhal.o
/home/nanos-secure-sdk/src/os_io_seproxyhal.c:25:10: fatal error: 'hci.h' file not found
#include "hci.h"
         ^
1 error generated.
make: *** [obj/os_io_seproxyhal.o] Error 1

**Comment by Moejoe90** [comment]
I am facing the same problem, these apps no longer build and if i revert to a previous version its ok however a previous version will naturally fail to run on the new firmware 1.3

**Comment by btchip** [comment]
Fixed by #4
