### ISSUE TITLE
make blue-app-helloworld fails, "No rule to make target ..."

### ISSUE THREAD

**Issue by jeremyawon** [LedgerHQ/blue-sample-apps#5]
make: *** No rule to make target `obj/main.o',

has anyone else encountered this?

**Comment by parkerhoyes** [comment]
That's very strange...

Make sure you have the latest version of this repository and you're on the latest version of the SDK (tag `nanos-1314` on `nanos-secure-sdk`).

If that doesn't work, could you try running make like this:

```
make clean all VERBOSE=1 > log.txt
```

And post the log here for me to debug? Feel free to hop into the [developer Slack](http://ledger-dev.slack.com/) for some assistance.

**Comment by jeremyawon** [comment]
```
~/Desktop/ledger/nanos-secure-sdk :git status                                                                          (1525802) 20:11:16
HEAD detached at nanos-1314
nothing to commit, working tree clean


(ledger) ~/Desktop/ledger/blue-sample-apps/blue-app-helloworld :make clean all VERBOSE=1                                (master) 20:12:06
TARGET_NAME=TARGET_NANOS TARGET_ID=0x31100002
BOLOS_ENV=/Users/jeremy/Desktop/ledger/bolos_env
rm -fr obj bin debug dep  
make: *** No rule to make target `obj/main.o', needed by `bin/app.elf'.  Stop.

```

**Comment by parkerhoyes** [comment]
What operating system are you running? Linux is the preferred option. macOS isn't particularly well supported. Windows should work with a bit of fiddling.

**Comment by jeremyawon** [comment]
yeah, i am on osx. i've restarted in an ubuntu vm and can build now 👍

am i right in thinking there is no device simulator? loading and running on device is the only way to test?

**Comment by parkerhoyes** [comment]
Correct, there is no device simulator at the moment
